# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./../flagStonePort/transform-util-cxx/transform-util
# Target is a library:  
QT       += core gui xml svg

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets
QMAKE_CFLAGS += -w -fpermissive
QMAKE_CXXFLAGS += -w -fpermissive -std=c++11

INCLUDEPATH += ../../transform-cxx-bsd \
               .
DESTDIR = $$PWD
# MinGW's "ar -M" script splits paths that contain spaces, so archive again with ar rcs.
DOLLAR = $
MAKE_OBJECTS = ~(OBJECTS)
MAKE_OBJECTS = $$replace(MAKE_OBJECTS, ~, $$DOLLAR)
LIBFILE = $$shell_quote($$clean_path($$DESTDIR/lib$${TARGET}.a))
QMAKE_POST_LINK = ar rcs $$LIBFILE $$MAKE_OBJECTS
CONFIG += release warn_off staticlib c++11
CONFIG -= debug warn_on 
TEMPLATE = lib 
HEADERS += FSCodec.h \
           FSImageConstructor.h \
           FSShapeConstructor.h \
           FSSoundConstructor.h \
           FSTextConstructor.h \
           FSTransformUtil.h \
           transformutil.h 
SOURCES += FSCodec.cpp \
           FSImageConstructor.cpp \
           FSShapeConstructor.cpp \
           FSSoundConstructor.cpp \
           FSTextConstructor.cpp \
           FSTransformUtil.cpp 
